### ISSUE TITLE
webpacker をひきはがす

### ISSUE THREAD

**Issue by tomada1114** [tmasuyama1114/ruby-knock#36]
## ゴール
Webpacker を使用しなくなる

## 経緯
Rails 7 からは webpacker が標準搭載ではなくなるため、今のうちにやめたい

## やること
参考
https://numb86-tech.hatenablog.com/entry/2019/01/10/211416

**Comment by tmasuyama1114** [comment]
webpack導入部分はこちらを参考
https://note.com/campfire_dev/n/n1686059962b5

**Comment by tomada1114** [comment]
ディレクトリ構成はここを参考にする
https://qiita.com/geek_shanshan/items/8f348734d95d9ece9576#%E8%84%B1webpacker
![image](https://user-images.githubusercontent.com/68495563/153698013-25869868-bf35-44ff-9f24-1e58ff7303b0.png)

**Comment by tomada1114** [comment]
webpackの導入は別issueでやる
